import type { Course } from "@/lib/course-types";
import { CodeBlock } from "@/components/CodeBlock";
import { Callout } from "@/components/Callout";
import { FolderPicker } from "@/components/FolderPicker";

export const FIRST_PR_COURSE: Course = {
  slug: "first-pr",
  title: "Your first PR",
  tagline: "A guided build: from a blank machine to a merged model in production",
  audience:
    "Hands-on, at your own machine. Assumes the Git essentials course (or equivalent git experience). Best done with real access — work through it your first week.",
  hours: "~3 hrs hands-on",
  accent: "var(--layer-reporting)",
  lessons: [
    // ------------------------------------------------------------------
    {
      slug: "set-up-your-machine",
      title: "Set up your machine",
      blurb: "Tools, credentials and a green dbt debug",
      minutes: 25,
      steps: [
        {
          id: "before",
          body: (
            <>
              <p>
                This course is hands-on: every lesson is <em>do this → you should
                see this → here&apos;s why</em>. Before starting you need three
                things from your team lead: a GitHub account added to the org,
                Snowflake access with the analyst role or higher, and the connection
                details (account identifier, role, warehouse).
              </p>
              <p>
                Setup is the slowest part of the whole course — and you only ever do
                it once.
              </p>
            </>
          ),
        },
        {
          id: "install",
          title: "Do: install the tools",
          body: (
            <>
              <ol>
                <li>
                  Install <strong>Git for Windows</strong> from git-scm.com
                  (defaults are fine).
                </li>
                <li>
                  Install <strong>VS Code</strong> if you don&apos;t have it.
                </li>
                <li>
                  Clone the repo — in a terminal:
                  <CodeBlock
                    lang="bash"
                    code={`git clone https://github.com/wnl-icb-analytics/dbt-analytics.git`}
                  />
                </li>
                <li>Open the cloned folder in VS Code.</li>
              </ol>
              <p>
                <strong>You should see:</strong> VS Code offers to install the
                workspace&apos;s recommended extensions — say yes; that includes the
                dbt extension, which gives you error-checking, autocomplete and
                lineage as you write.
              </p>
            </>
          ),
        },
        {
          id: "script",
          title: "Do: open a terminal",
          body: (
            <>
              <p>
                Open a terminal in VS Code (<code>Ctrl+`</code>). The project&apos;s
                setup script, <code>start_dbt.ps1</code>, runs automatically — it
                configures git hooks, installs the dbt engine (called Fusion),
                prepares the Python tooling for helper scripts, and loads your
                connection settings.
              </p>
              <p>
                <strong>You should see:</strong> since this is your first run with
                no <code>.env</code> file, it walks you through creating one —
                prompting for the account identifier, your username, role and
                warehouse (the details from your team lead), then asking how to
                authenticate. Pick option 1 (browser SSO) unless you have been given
                a token.
              </p>
              <Callout kind="warn" title="Why a .env file?">
                <p>
                  Credentials never go in the repo — the repo is public. The{" "}
                  <code>.env</code> file lives only on your machine and git is
                  configured to ignore it. The script writes it for you; you never
                  paste secrets into project files.
                </p>
              </Callout>
            </>
          ),
          check: {
            prompt: "Why does the .env file exist outside version control?",
            options: [
              "It changes too often to be worth committing",
              "It holds your credentials, and the repo is public — secrets stay on your machine only",
              "git cannot store configuration files",
              "It is regenerated by the setup script every day",
            ],
            answer: 1,
            explain:
              "Anything committed to this repo is on the public internet. Connection details and tokens live in .env, which .gitignore keeps out of every commit automatically.",
          },
        },
        {
          id: "signing",
          title: "Do: set up commit signing (one-off)",
          body: (
            <>
              <p>
                This repo requires commits to be <em>signed</em> — cryptographic
                proof that a commit really came from you. One-time setup, in the
                terminal:
              </p>
              <CodeBlock
                lang="bash"
                code={`
ssh-keygen -t ed25519 -C "you@nhs.net"
git config --global gpg.format ssh
git config --global user.signingkey ~/.ssh/id_ed25519.pub
git config --global commit.gpgsign true
`}
              />
              <p>
                Then add the key at{" "}
                <a
                  href="https://github.com/settings/keys"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  GitHub Settings → SSH and GPG keys
                </a>{" "}
                → <em>New SSH key</em>.{" "}
                <strong>The key-type dropdown defaults to Authentication Key —
                change it to Signing Key</strong>, or your commits will still count
                as unsigned.
              </p>
            </>
          ),
        },
        {
          id: "debug",
          title: "Do: prove the connection works",
          body: (
            <>
              <CodeBlock lang="bash" code={`dbt debug`} />
              <p>
                <strong>You should see:</strong> a series of checks ending in{" "}
                <strong>“All checks passed!”</strong> — possibly after a browser
                window opens for Snowflake sign-in.
              </p>
              <p>
                <strong>If it fails:</strong> the cause is almost always the{" "}
                <code>.env</code> — a typo in the account identifier or a role you
                don&apos;t have yet. Fix the value in <code>.env</code>, open a new
                terminal (so it reloads), and run <code>dbt debug</code> again.
              </p>
              <p>
                Green? Your machine is done — permanently. Everything from here is
                the actual work.
              </p>
            </>
          ),
          check: {
            prompt: "dbt debug fails to connect. Where do you look first?",
            options: [
              "Reinstall dbt",
              "The .env file — a wrong account identifier or role is the usual cause",
              "Snowflake's status page",
              "The dbt_project.yml file",
            ],
            answer: 1,
            explain:
              "dbt debug tests connection + config, and the connection details come from .env. Check those values, open a fresh terminal so they reload, retry — that resolves nearly every first-day failure.",
          },
        },
      ],
    },
    // ------------------------------------------------------------------
    {
      slug: "pick-your-table",
      title: "Pick your table",
      blurb: "Choose familiar data and state its grain",
      minutes: 10,
      steps: [
        {
          id: "familiar",
          body: (
            <>
              <p>
                You are about to build your first model. The single best decision
                you can make now: <strong>build it on data you already know</strong>{" "}
                — a reference table you maintain, a feed you have queried for
                reports. You are learning dbt&apos;s mechanics; don&apos;t make
                yourself learn an unfamiliar dataset at the same time.
              </p>
              <p>
                Your existing judgement is the test harness: you can glance at the
                output and know whether it looks right.
              </p>
            </>
          ),
        },
        {
          id: "grain",
          title: "Do: state the grain in one sentence",
          body: (
            <>
              <p>
                Before any SQL, answer: <strong>one row per what?</strong> One row
                per site per weekday? Per patient per referral per week? Write the
                sentence down — it decides your tests later, and not being able to
                say it is the signal you don&apos;t know the table well enough yet.
              </p>
              <p>
                <strong>You should have:</strong> a table in mind, and its grain in
                one sentence. The rest of the course uses a practice-opening-hours
                reference table (“one row per site per day of week”) as its example —
                substitute yours throughout.
              </p>
            </>
          ),
          check: {
            prompt: "Why insist on stating the grain before writing SQL?",
            options: [
              "dbt requires it in configuration",
              "It defines what unique means for this table — which becomes your most important test",
              "It determines which warehouse the model uses",
              "It is needed for the file name",
            ],
            answer: 1,
            explain:
              "The grain is the table's contract: one row per what. Your grain test (next lessons) asserts it forever — and a join that breaks it is the most common serious modelling bug.",
          },
        },
      ],
    },
    // ------------------------------------------------------------------
    {
      slug: "find-or-add-the-source",
      title: "Find — or add — the source",
      blurb: "The raw layer, and exactly what to do when your table isn't in it",
      minutes: 25,
      steps: [
        {
          id: "recap",
          body: (
            <>
              <p>
                Every model starts from a <strong>raw model</strong> — the generated
                1:1 view that renames a source table&apos;s columns to clean
                snake_case (the why is in the handbook&apos;s sources page; short
                version: supplier column names like{" "}
                <code>&quot;UNIQUE SUBMISSION ID&quot;</code> are handled once, by a
                script, so nobody deals with them downstream).
              </p>
              <p>So step one is always: does the raw model already exist?</p>
            </>
          ),
        },
        {
          id: "search",
          title: "Do: search for the raw model",
          body: (
            <>
              <p>
                In VS Code press <code>Ctrl+P</code> and type{" "}
                <code>raw_</code> plus a guess at your table&apos;s name:
              </p>
              <CodeBlock lang="text" code={`raw_reference_opening`} />
              <p>
                <strong>If you find it:</strong> open it. The column list (already
                cleaned) is what you have to work with. Preview real rows:
              </p>
              <CodeBlock lang="bash" code={`dbt show -s raw_reference_opening_hours`} />
              <p>
                You are done with this lesson — jump ahead via Continue. The
                remaining steps cover what to do when the search comes up empty.
              </p>
            </>
          ),
        },
        {
          id: "decide",
          title: "No raw model? Decide which case you're in",
          body: (
            <>
              <p>
                The table exists in the Snowflake data lake but has no raw model.
                There are exactly three cases, and one question decides:{" "}
                <strong>is the table&apos;s schema already known to the project?</strong>{" "}
                Open <code>source_mappings.yml</code> (repo root) and look for the
                table&apos;s database and schema.
              </p>
              <table>
                <thead>
                  <tr>
                    <th>Case</th>
                    <th>What you do</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>Schema is mapped (no <code>manual: true</code>)</td>
                    <td>Run the pipeline — next step</td>
                  </tr>
                  <tr>
                    <td>Schema is mapped with <code>manual: true</code></td>
                    <td>Add the table to its manual YAML — step after</td>
                  </tr>
                  <tr>
                    <td>Schema isn&apos;t in the file at all</td>
                    <td>A new feed — pair with the team rather than solo</td>
                  </tr>
                </tbody>
              </table>
            </>
          ),
        },
        {
          id: "auto",
          title: "Case 1 — mapped schema: run the pipeline",
          body: (
            <>
              <CodeBlock
                lang="bash"
                code={`python scripts/sources/run_all_source_generation.py`}
              />
              <p>
                The pipeline inspects the live schema and generates everything for
                every table it finds — including yours.
              </p>
              <p>
                <strong>You should see:</strong> a new entry in the schema&apos;s{" "}
                <code>auto_*.yml</code> under <code>models/sources/</code>, and a new{" "}
                <code>raw_…sql</code> file under <code>models/raw/&lt;domain&gt;/</code>.
                Commit both generated files with your work.
              </p>
            </>
          ),
        },
        {
          id: "manual",
          title: "Case 2 — volatile schema: add to the manual YAML",
          body: (
            <>
              <p>
                Schemas marked <code>manual: true</code> (like analyst-managed
                uploads) use a curated table list, so a stray upload can&apos;t
                silently become a source. Add your table to the schema&apos;s{" "}
                <code>manual_*.yml</code> in <code>models/sources/</code> — copy an
                existing table block and edit the name and columns:
              </p>
              <CodeBlock
                lang="yaml"
                code={`
  - name: OPENING_HOURS
    identifier: '"OPENING_HOURS"'
    columns:
      - name: SITE_CODE
        data_type: TEXT
      - name: DAY_OF_WEEK
        data_type: NUMBER(2,0)
`}
              />
              <p>
                Then run the same pipeline command as case 1.{" "}
                <strong>You should see:</strong> a generated raw model for your
                table; column types in your YAML are synced against the live schema,
                and any mismatch prints a drift warning to fix.
              </p>
            </>
          ),
          check: {
            prompt:
              "Your table is in a manual: true schema. Why won't running the pipeline alone pick it up?",
            options: [
              "Manual schemas need a server restart",
              "Manual schemas use a curated list — only tables named in the manual YAML get sources and raw models",
              "The pipeline only runs in CI",
              "It will — manual: true only affects documentation",
            ],
            answer: 1,
            explain:
              "manual: true means a person, not Snowflake's metadata, decides which tables count. Add the table to the manual YAML first; the pipeline then generates its raw model like any other.",
          },
        },
        {
          id: "never-edit",
          title: "One rule, either case",
          body: (
            <>
              <Callout kind="warn" title="Never hand-edit generated files">
                <p>
                  Everything under <code>models/raw/</code> and every{" "}
                  <code>auto_*.yml</code> is regenerated on each pipeline run — hand
                  edits are silently overwritten. Wrong column name? Fix it in the
                  generator config or the manual YAML, never in the output.
                </p>
              </Callout>
            </>
          ),
        },
      ],
    },
    // ------------------------------------------------------------------
    {
      slug: "where-does-it-go",
      title: "Where does it go?",
      blurb: "Layers × domains: choosing the folder (it chooses your config)",
      minutes: 12,
      steps: [
        {
          id: "why-folders",
          body: (
            <>
              <p>
                In this project, the folder you put a file in is not tidiness — it{" "}
                <strong>is</strong> configuration. The folder decides whether your
                model builds as a view or table, which database and schema it lands
                in, what tags and governance hooks it gets. Choose the folder and
                you have configured the model.
              </p>
              <p>
                The choice is two simple questions: which <strong>layer</strong>{" "}
                (what job is the model doing) and which <strong>domain</strong>{" "}
                (what data is it about).
              </p>
            </>
          ),
        },
        {
          id: "picker",
          title: "Try it",
          body: (
            <>
              <FolderPicker />
              <p>
                For our worked example — cleaning one reference table about sites —
                the answers are <em>staging</em> + <em>shared reference</em>:{" "}
                <code>models/staging/shared/</code>, file starting{" "}
                <code>stg_</code>.
              </p>
            </>
          ),
          check: {
            prompt:
              "You're building a model that joins GP observations to derive a reusable smoking-status block. Folder?",
            options: [
              "models/staging/olids/ — it reads staged data",
              "models/modelling/olids/ — joins and reusable derivations are modelling-layer work",
              "models/reporting/olids/ — analysts will use it",
              "models/modelling/commissioning/ — derivations live under commissioning",
            ],
            answer: 1,
            explain:
              "Job first: joining and deriving a reusable block = modelling (int_). Data second: GP observations = olids. Staging never joins; reporting is for assembled analyst-facing datasets that would ref() this block.",
          },
        },
        {
          id: "name",
          title: "Do: create the file",
          body: (
            <>
              <p>
                Name = layer prefix + source + table, matching the raw model:
              </p>
              <CodeBlock
                lang="text"
                code={`models/staging/shared/stg_reference_opening_hours.sql`}
              />
              <p>
                <strong>You should have:</strong> an empty <code>.sql</code> file in
                the right folder. That empty file is already configured — the
                staging folder will make it a view in the staging schema.
              </p>
            </>
          ),
        },
      ],
    },
    // ------------------------------------------------------------------
    {
      slug: "write-the-model",
      title: "Write the model",
      blurb: "One SELECT, project style, previewed as you go",
      minutes: 20,
      steps: [
        {
          id: "write",
          body: (
            <>
              <p>
                A staging model is one SELECT from the raw model: explicit columns,
                light cleaning, renames to conventions. Write yours; for the worked
                example:
              </p>
              <CodeBlock
                lang="sql"
                title="stg_reference_opening_hours.sql"
                code={`
select
    organisation_code,
    upper(trim(site_code)) as site_code,
    day_of_week,
    opens_at::time as opens_at,
    closes_at::time as closes_at,
    is_open_24h::boolean as is_open_24h
from {{ ref('raw_reference_opening_hours') }}
`}
              />
              <p>Why each choice:</p>
              <ul>
                <li>
                  <code>ref()</code>, never a hardcoded table — dbt fills in the
                  right database per environment and learns the dependency.
                </li>
                <li>
                  <strong>Explicit columns</strong>, no <code>select *</code> — you
                  are defining the interface downstream models will rely on.
                </li>
                <li>
                  <strong>No joins, no filters with business meaning</strong> — the
                  moment you want one, that is a modelling-layer (<code>int_</code>)
                  model instead.
                </li>
                <li>
                  <strong>Lowercase keywords</strong> — the linter in CI checks it.
                </li>
              </ul>
            </>
          ),
        },
        {
          id: "preview",
          title: "Do: look at it before building it",
          body: (
            <>
              <CodeBlock
                lang="bash"
                code={`
dbt show -s stg_reference_opening_hours    # run the SELECT, print 5 rows
dbt compile                                # render every model to plain SQL
`}
              />
              <p>
                <strong>You should see:</strong> five sensible-looking rows from{" "}
                <code>dbt show</code>; and <code>dbt compile</code> finishing in
                seconds with no errors. While you type, the dbt extension is doing
                the same checking live — a red underline now is an error{" "}
                <code>dbt build</code> would have given you later.
              </p>
              <p>
                <strong>If show fails:</strong> read the message — a misspelled{" "}
                <code>ref()</code> names the model it can&apos;t find; a SQL error
                points at the line.
              </p>
            </>
          ),
          check: {
            prompt: "Why explicit columns rather than select * in staging?",
            options: [
              "select * is slower in Snowflake",
              "The column list is the interface downstream models depend on — * silently changes when the source does",
              "dbt cannot compile select *",
              "It makes the file longer, which reviewers prefer",
            ],
            answer: 1,
            explain:
              "With *, a new upstream column appears downstream unannounced, and a removed one breaks consumers without warning. Naming columns makes the model's contract explicit and changes deliberate.",
          },
        },
      ],
    },
    // ------------------------------------------------------------------
    {
      slug: "describe-and-test",
      title: "Describe and test it",
      blurb: "Eight lines of YAML, written by hand, that work forever",
      minutes: 20,
      steps: [
        {
          id: "why-yaml",
          body: (
            <>
              <p>
                Next to your <code>.sql</code> goes a <code>.yml</code> file with
                the same name. It does three jobs: names an owner, documents the
                columns, and declares <strong>tests</strong> — assertions checked on
                every build, forever. CI requires it; more importantly, it is where
                your knowledge of the data gets written down.
              </p>
              <p>
                Write it by hand — it is short, and writing it is how you make the
                decisions it contains:
              </p>
              <CodeBlock
                lang="yaml"
                title="stg_reference_opening_hours.yml"
                code={`
models:
  - name: stg_reference_opening_hours
    description: Site opening hours reference, one row per site per day of week
    config:
      meta:
        owner:
          name: Your Name
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns: [site_code, day_of_week]
    columns:
      - name: site_code
        description: Standardised site identifier
        data_tests: [not_null]
      - name: day_of_week
        description: ISO day of week (1 = Monday)
        data_tests: [not_null]
`}
              />
            </>
          ),
        },
        {
          id: "anatomy",
          title: "What each part does",
          body: (
            <>
              <ul>
                <li>
                  <strong>description</strong> — note it states the grain. Ends up in
                  dbt docs and as a Snowflake comment.
                </li>
                <li>
                  <strong>owner</strong> — every model names a human; CI checks.
                </li>
                <li>
                  <strong>the grain test</strong> — remember your one-sentence grain?{" "}
                  <code>unique_combination_of_columns</code> on those columns is the
                  single most valuable test you can write: it fails the moment
                  anything duplicates rows.
                </li>
                <li>
                  <strong>not_null</strong> on the key columns the grain depends on.
                </li>
              </ul>
              <p>
                Three tests is right for a staging model. Every test compiles to a
                query that hunts for violating rows — zero rows back means pass.
              </p>
            </>
          ),
          check: {
            prompt:
              "Your grain is one row per site per weekday. Which single test catches a future join accidentally duplicating rows?",
            options: [
              "not_null on site_code",
              "unique on site_code",
              "unique_combination_of_columns on [site_code, day_of_week]",
              "A row-count test",
            ],
            answer: 2,
            explain:
              "unique on site_code alone would fail now (each site has 7 rows). Only the combination test matches your actual grain — and it fires the moment anything fans the table out.",
          },
        },
        {
          id: "agents",
          title: "On tooling and agents",
          body: (
            <>
              <p>
                AI assistants write competent YAML, and a generator command exists
                that scaffolds the column list from the built model (see the command
                reference). Use either to save typing — but notice what cannot be
                delegated: <em>what is the grain, which columns matter, what does
                null mean here</em>. Those are your decisions; tools are the junior
                partner that types them up.
              </p>
            </>
          ),
        },
      ],
    },
    // ------------------------------------------------------------------
    {
      slug: "build-and-test",
      title: "Build it",
      blurb: "One command runs the model and its tests in your dev schema",
      minutes: 15,
      steps: [
        {
          id: "build",
          body: (
            <>
              <CodeBlock lang="bash" code={`dbt build -s stg_reference_opening_hours`} />
              <p>
                <code>build</code> = run the model <em>and</em> its tests, in
                order, in <strong>your dev schema</strong> — a sandbox copy of the
                warehouse keyed to you. Nothing you do here touches production.
              </p>
              <p>
                <strong>You should see:</strong>
              </p>
              <CodeBlock
                lang="text"
                code={`
1 of 4 OK created sql view model ...stg_reference_opening_hours  [SUCCESS]
2 of 4 PASS not_null_..._site_code                               [PASS]
3 of 4 PASS not_null_..._day_of_week                             [PASS]
4 of 4 PASS dbt_utils_unique_combination_of_columns_...          [PASS]
Completed successfully
`}
              />
            </>
          ),
        },
        {
          id: "fail",
          title: "If a test fails",
          body: (
            <>
              <p>
                A FAIL line prints the count of violating rows. This is not a
                setback — <strong>your test just told you something true about the
                data</strong> that nobody had written down. The usual first-model
                discoveries:
              </p>
              <ul>
                <li>
                  <strong>Grain test fails</strong> — the source has duplicates you
                  didn&apos;t expect. Investigate: is your grain sentence wrong, or
                  is the feed dirty? Either answer is progress.
                </li>
                <li>
                  <strong>not_null fails</strong> — nulls are real. Decide whether
                  the column is genuinely optional (drop the test, document the
                  meaning of null) or the rows are junk worth flagging to the team.
                </li>
              </ul>
              <p>
                Investigate with <code>dbt show -s your_model --limit 20</code>, or
                run the failing test&apos;s compiled SQL from{" "}
                <code>target/compiled/</code> to see the exact offending rows.
              </p>
            </>
          ),
          check: {
            prompt:
              "Your grain test fails with 14 duplicate site/day pairs. What does that mean?",
            options: [
              "Your YAML is misconfigured",
              "dbt built the model twice",
              "The data genuinely contains duplicates your grain didn't expect — investigate before changing anything",
              "Snowflake's cache is stale; rebuild",
            ],
            answer: 2,
            explain:
              "The test ran a real query against real rows. Either your understanding of the grain is incomplete or the feed has a quality issue — both are findings worth a sentence in your PR description.",
          },
        },
        {
          id: "green",
          title: "Do: get to green",
          body: (
            <>
              <p>
                Iterate — edit, <code>dbt build -s stg_reference_opening_hours</code>,
                read — until everything passes.{" "}
                <strong>You should have:</strong> a fully green build, and (worth the
                30 seconds) a look at your actual table in Snowflake, sitting in your
                dev schema.
              </p>
            </>
          ),
        },
      ],
    },
    // ------------------------------------------------------------------
    {
      slug: "open-the-pr",
      title: "Open the PR",
      blurb: "Branch, commit, push, propose — then watch the checks",
      minutes: 20,
      steps: [
        {
          id: "branch-commit",
          body: (
            <>
              <p>
                Time for the git loop from the essentials course — for real this
                time. If you have been working on <code>main</code> locally, no harm
                done: creating the branch now takes your changes with it.
              </p>
              <CodeBlock
                lang="bash"
                code={`
git switch -c feat/opening-hours-staging
git status
`}
              />
              <p>
                <strong>You should see:</strong> your <code>.sql</code> and{" "}
                <code>.yml</code> listed as untracked/modified — and nothing else.
                If generated source files from earlier are listed, they belong in
                this PR too. Anything you don&apos;t recognise: don&apos;t stage it.
              </p>
              <CodeBlock
                lang="bash"
                code={`
git add models/staging/shared/stg_reference_opening_hours.sql
git add models/staging/shared/stg_reference_opening_hours.yml
git commit -m "feat: add opening hours staging model"
git push
`}
              />
            </>
          ),
        },
        {
          id: "pr",
          title: "Do: open the pull request",
          body: (
            <>
              <p>
                <strong>You should see:</strong> the push output includes a “Create a
                pull request” link — click it (or run <code>gh pr create</code>).
                Write a description a stranger could follow:
              </p>
              <CodeBlock
                lang="text"
                code={`
## What
Adds stg_reference_opening_hours: one row per site per weekday.

## Why
Needed for the access dashboard; nothing currently stages this table.

## Checks
- dbt build green locally; grain verified on (site_code, day_of_week)
- ~40 rows have null closes_at where is_open_24h = true - kept, noted in column description
`}
              />
              <p>
                That third section — what you checked and what you noticed — is the
                habit that makes reviews fast.
              </p>
            </>
          ),
        },
        {
          id: "checks",
          title: "Then: watch what happens",
          body: (
            <>
              <p>
                <strong>You should see, within a couple of minutes:</strong> checks
                appearing at the bottom of the PR (compile, code quality, ownership)
                and <strong>CodeRabbit</strong> — an automated reviewer — commenting
                on your diff. A human reviewer is auto-assigned; once they are, the
                heavier validation check builds your changed models in a shared dev
                environment.
              </p>
              <p>
                While you wait, read your own diff in the Files changed tab.
                Everyone finds something.
              </p>
            </>
          ),
          check: {
            prompt: "CodeRabbit leaves a comment you're fairly sure is wrong. You should…",
            options: [
              "Apply it anyway — automated reviewers are authoritative",
              "Ignore it silently",
              "Reply explaining why you're keeping it as is — disagreeing with reasons is a normal review response",
              "Close the PR and re-open to clear the comments",
            ],
            answer: 2,
            explain:
              "Automated review comments are suggestions, not gates. Address the valid ones, push back on the rest in a reply — the human reviewer sees both the comment and your reasoning.",
          },
        },
      ],
    },
    // ------------------------------------------------------------------
    {
      slug: "merge-and-after",
      title: "Merge — and what happens next",
      blurb: "Responding to review, landing on main, and your model's new life",
      minutes: 15,
      steps: [
        {
          id: "respond",
          body: (
            <>
              <p>
                Review comments arrive. The loop for each: make the change locally,
                then —
              </p>
              <CodeBlock
                lang="bash"
                code={`
git add -u
git commit -m "fix: rename site identifier to match conventions"
git push
`}
              />
              <p>
                — and <strong>reply to the comment</strong> (“done in abc123”) so the
                reviewer doesn&apos;t have to re-read your whole diff. Disagree with
                a comment? Say why in the thread; reviewers are often missing
                context you have.
              </p>
            </>
          ),
        },
        {
          id: "merge",
          title: "Do: merge",
          body: (
            <>
              <p>
                Approval plus green checks unlocks the merge button. We
                squash-merge: your branch&apos;s commits become one tidy commit on
                main. Delete the branch when GitHub offers, then locally:
              </p>
              <CodeBlock
                lang="bash"
                code={`
git switch main
git pull
`}
              />
              <p>
                <strong>You should see:</strong> your model in the pulled main — and
                shortly after the merge, the deploy workflow building it into
                production Snowflake.
              </p>
            </>
          ),
        },
        {
          id: "after",
          title: "Your model's new life",
          body: (
            <>
              <p>From tonight, without you doing anything:</p>
              <ul>
                <li>the nightly build rebuilds your model and runs your tests;</li>
                <li>
                  if the feed changes in six months, your grain test raises the
                  alarm — to the team, before any dashboard is wrong;
                </li>
                <li>
                  your column descriptions are live in dbt docs and as Snowflake
                  comments;
                </li>
                <li>anyone can <code>ref()</code> your model and build on it.</li>
              </ul>
              <p>
                That is the full loop, and it is the same loop for everything from a
                one-line fix to a new disease register. It felt heavyweight this
                time; from the second PR on, the loop is minutes.
              </p>
            </>
          ),
          check: {
            prompt: "Six months on, the feed starts sending duplicate rows. Who finds out, and how?",
            options: [
              "A dashboard user notices odd numbers and emails around",
              "The nightly build — your grain test fails and the team sees it before any output is consumed",
              "Nobody, unless someone re-checks the model",
              "Snowflake blocks the duplicate rows automatically",
            ],
            answer: 1,
            explain:
              "This is the payoff of the YAML you wrote in twenty minutes: your understanding of the data became an assertion that runs every night, forever, guarding everyone downstream of you.",
          },
        },
      ],
    },
  ],
};
