import type { Metadata } from "next";
import { LessonShell } from "@/components/LessonShell";
import { CodeBlock } from "@/components/CodeBlock";
import { Callout } from "@/components/Callout";
import { LayerCake } from "@/components/LayerCake";
import { LayerSorter } from "@/components/LayerSorter";

export const metadata: Metadata = { title: "The layer cake" };

export default function Page() {
  return (
    <LessonShell
      section="learn"
      slug="layer-cake"
      kicker="Learn 02"
      title="The layer cake"
      lede="Five layers, each with exactly one job. Once you can name the job, you know where any model belongs — and what it is not allowed to do."
      minutes={8}
    >
      <p>
        Models in <code>dbt-analytics</code>{" "}are organised under{" "}
        <code>models/</code>{" "}into layers. Data flows upward: raw renames, staging cleans,
        modelling builds blocks, reporting assembles, published governs. Click each layer:
      </p>

      <LayerCake />

      <h2>The rules per layer</h2>

      <h3>Raw — rename, nothing else</h3>
      <p>
        Each raw model is a 1:1 view over a source table that just renames columns to{" "}
        <code>snake_case</code>. They are generated by scripts —{" "}
        <strong>you never write or edit a raw model by hand</strong>.
      </p>
      <CodeBlock
        lang="sql"
        title="models/raw/commissioning/raw_csds_activesubmission.sql (auto-generated)"
        code={`
select
    "UNIQUE SUBMISSION ID" as unique_submission_id
from {{ source('csds', 'ActiveSubmission') }}
`}
      />

      <h3>Staging — clean and standardise</h3>
      <p>
        One staging model per source table: rename to project conventions (for example{" "}
        <code>pseudo_nhs_number</code> → <code>sk_patient_id</code>), cast types, light
        cleaning. <strong>No joins, no business logic.</strong>{" "}Staging is the stable
        foundation everything downstream relies on.
      </p>

      <Callout kind="info" title="Where raw and staging build">
        <p>
          Both layers use the <code>STAGING</code>{" "}database. All raw models build in
          its single <code>DBT_RAW</code>{" "}schema. Staging models use source or domain
          schemas such as <code>CSDS</code>, <code>OLIDS</code>{" "}and
          <code>REFERENCE</code>. Development uses the matching layout in
          <code>DEV__STAGING</code>.
        </p>
      </Callout>

      <h3>Modelling — reusable building blocks</h3>
      <p>
        Prefixed <code>int_</code>. This is where real work happens: joins across staging
        models, derivations, focused logic that more than one downstream model can reuse.
        For example <code>int_wl_current</code>{" "}filters the waiting list to the latest
        snapshot week, joins specialty and provider lookups, and derives{" "}
        <code>days_on_waiting_list</code>.
      </p>

      <h3>Reporting — analytics-ready datasets</h3>
      <p>
        Dimensions (<code>dim_</code>) and facts (<code>fct_</code>) that analysts query
        directly — like <code>dim_person_demographics</code>: one row per person, joined
        to gender, ethnicity, geography and practice lookups. You will also see{" "}
        <code>pit_</code>{" "}(point-in-time), <code>obt_</code>{" "}(one big table) and{" "}
        <code>dq_</code>{" "}(data quality) prefixes here.
      </p>
      <p>
        This layer is where most of your work <em>starts</em>, not where it ends: when
        a question lands, check what already exists in reporting before building
        anything. The fastest model is the one someone already wrote, tested and
        refreshes nightly.
      </p>

      <h3>Published — governed outputs</h3>
      <p>
        Datasets that power dashboards and external consumers, split by legal basis:{" "}
        <code>direct_care/</code>{" "}and <code>secondary_use/</code>. Secondary-use models
        apply national opt-out filtering via an inner join to{" "}
        <code>dim_person_secondary_use_allowed</code>. Governance (ownership grants,
        Snowflake tags) is applied automatically by post-hooks.
      </p>

      <Callout kind="info" title="There is a sixth layer">
        <p>
          <code>models/semantic/</code>{" "}holds Snowflake Semantic Views (
          <code>sem_</code>) — pre-defined facts, dimensions and metrics that give
          downstream query tools an agreed definition of the data. You will meet these
          in the Going further section; they follow the same ref() rules.
        </p>
      </Callout>

      <h2>Why so strict?</h2>
      <p>
        Because every rule removes a question. If joins are banned in staging, you never
        wonder whether <code>stg_csds_bridging</code>{" "}hides logic — it cannot. If only
        published models feed dashboards, you know exactly what is safe to refactor.
        Layers turn “where should this go?” from a debate into a lookup:
      </p>
      <table>
        <thead>
          <tr>
            <th>You are about to…</th>
            <th>It belongs in</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Rename or cast columns from one source table</td>
            <td>
              <code>staging/</code>
            </td>
          </tr>
          <tr>
            <td>Join staging models or derive a reusable measure</td>
            <td>
              <code>modelling/</code>{" "}(<code>int_</code>)
            </td>
          </tr>
          <tr>
            <td>Assemble a person/provider-level dataset for analysis</td>
            <td>
              <code>reporting/</code>{" "}(<code>dim_</code>/<code>fct_</code>)
            </td>
          </tr>
          <tr>
            <td>Feed a dashboard or share outside the team</td>
            <td>
              <code>published/</code>
            </td>
          </tr>
        </tbody>
      </table>

      <Callout kind="tip" title="Folders do real work">
        <p>
          In the OLIDS domain the Snowflake schema is derived from the folder path:{" "}
          <code>models/modelling/olids/diagnoses/</code>{" "}builds into{" "}
          <code>MODELLING.OLIDS_DIAGNOSES</code>. Create a folder and the schema follows —
          no config needed.
        </p>
      </Callout>

      <h2>Try it</h2>
      <LayerSorter />
    </LessonShell>
  );
}
