export type Layer = {
  id: string;
  name: string;
  prefix: string;
  job: string;
  detail: string;
  example: string;
  materialized: string;
  database: string;
  color: string; // css var
};

export const LAYERS: Layer[] = [
  {
    id: "raw",
    name: "Raw",
    prefix: "raw_",
    job: "Rename, nothing else",
    detail:
      "A 1:1 view of each source table with clean snake_case column names. Auto-generated by the source scripts — you never edit these by hand.",
    example: "raw_csds_bridging",
    materialized: "view",
    database: "STAGING.DBT_RAW",
    color: "var(--layer-raw)",
  },
  {
    id: "staging",
    name: "Staging",
    prefix: "stg_",
    job: "Clean and standardise",
    detail:
      "One model per source table. Rename to project conventions, cast types, light cleaning. No joins, no business logic — ever.",
    example: "stg_csds_bridging",
    materialized: "view",
    database: "STAGING.CSDS",
    color: "var(--layer-staging)",
  },
  {
    id: "modelling",
    name: "Modelling",
    prefix: "int_",
    job: "Build reusable blocks",
    detail:
      "Modular components: joins, derivations, focused logic that more than one downstream model can use. This is where most analyst work happens.",
    example: "int_wl_current",
    materialized: "table",
    database: "MODELLING.COMMISSIONING_MODELLING",
    color: "var(--layer-modelling)",
  },
  {
    id: "reporting",
    name: "Reporting",
    prefix: "dim_ / fct_",
    job: "Assemble analytics-ready datasets",
    detail:
      "Dimensions and facts that analysts query directly. Joins modelling blocks with dimensional lookups; rich documentation expected.",
    example: "dim_person_demographics",
    materialized: "table",
    database: "REPORTING.COMMISSIONING_REPORTING",
    color: "var(--layer-reporting)",
  },
  {
    id: "published",
    name: "Published",
    prefix: "(domain name)",
    job: "Govern and serve",
    detail:
      "Production datasets behind dashboards. Governance baked in: ownership grants, Snowflake tags, and opt-out filtering for secondary use.",
    example: "population_health_needs_base",
    materialized: "table",
    database: "PUBLISHED_REPORTING__*",
    color: "var(--layer-published)",
  },
];

/** descriptions used by the layer-sorter quiz */
export const SORTER_ITEMS: { text: string; layer: string }[] = [
  {
    text: "Joins three staging models and derives days_on_waiting_list",
    layer: "modelling",
  },
  {
    text: "Renames \"UNIQUE SUBMISSION ID\" to unique_submission_id — and nothing else",
    layer: "raw",
  },
  {
    text: "One row per person with demographics, queried directly by analysts",
    layer: "reporting",
  },
  {
    text: "Casts pseudo_nhs_number to sk_patient_id from a single raw model, no joins",
    layer: "staging",
  },
  {
    text: "Feeds a live dashboard and applies opt-out filtering for secondary use",
    layer: "published",
  },
];
